from PyQt5 import QtWidgets
from gui.appUI import MainWindow

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     homeWin = HomeWin()
#     homeWin.show()
#     sys.exit(app.exec_())

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
#
# class Ui_homeWindow(object):
#     def setupUi(self, homeWindow):
#         homeWindow.setObjectName("homeWindow")
#         homeWindow.resize(1077, 703)
#         icon = QtGui.QIcon()
#         icon.addPixmap(QtGui.QPixmap("gui/media/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         homeWindow.setWindowIcon(icon)
#         homeWindow.setWindowOpacity(1.0)
#         homeWindow.setAutoFillBackground(False)
#         self.centralwidget = QtWidgets.QWidget(homeWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.homeBG = QtWidgets.QLabel(self.centralwidget)
#         self.homeBG.setGeometry(QtCore.QRect(-4, -8, 1081, 711))
#         self.homeBG.setText("")
#         self.homeBG.setPixmap(QtGui.QPixmap("gui/media/BG.jpg"))
#         self.homeBG.setScaledContents(True)
#         self.homeBG.setObjectName("homeBG")
#         homeWindow.setCentralWidget(self.centralwidget)
#
#         self.retranslateUi(homeWindow)
#         QtCore.QMetaObject.connectSlotsByName(homeWindow)
#
#     def retranslateUi(self, homeWindow):
#         _translate = QtCore.QCoreApplication.translate
#         homeWindow.setWindowTitle(_translate("homeWindow", "Chemistry Papa"))
#
#

# from PyQt5 import QtWidgets
# from PyQt5.QtCore import Qt
# from PyQt5.QtGui import QTextCharFormat
#
#
# class Widget(QtWidgets.QWidget):
#     def __init__(self, parent = None):
#         super().__init__(parent)
#         self.text_box = QtWidgets.QTextEdit(self)
#         layout = QtWidgets.QVBoxLayout(self)
#         layout.addWidget(self.text_box)
#
#     def keyPressEvent(self, event):
#         if event.modifiers() == Qt.ShiftModifier and event.key() == Qt.Key_F6:
#             cursor = self.text_box.textCursor()
#             format = cursor.charFormat()
#             if format.verticalAlignment() == QTextCharFormat.AlignSubScript:
#                 vert = QTextCharFormat.AlignNormal
#             else:
#                 vert = QTextCharFormat.AlignSubScript
#             format.setVerticalAlignment(vert)
#             cursor.setCharFormat(format)
#
#
# if __name__ == "__main__":
#     app = QtWidgets.QApplication([])
#     w = Widget()
#     w.show()
#     app.exec()

#####################################################################
if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)

    uiMainWindow = MainWindow()
    uiMainWindow.setFixedSize(1000, 650)
    uiMainWindow.show()

    sys.exit(app.exec_())
#####################################################################
# import sys
#
# # from PyQt4.QtGui import QApplication, QMainWindow, QPushButton, QWidget
# #For PyQt5 :
# from PyQt5.QtWidgets import QApplication , QMainWindow , QPushButton , QWidget
# class UIWindow(object):
#     def setupUI(self, MainWindow):
#         MainWindow.setGeometry(50, 50, 400, 450)
#         MainWindow.setFixedSize(400, 450)
#         MainWindow.setWindowTitle("UIWindow")
#         self.centralwidget = QWidget(MainWindow)
#         # mainwindow.setWindowIcon(QtGui.QIcon('PhotoIcon.png'))
#         self.ToolsBTN = QPushButton('text', self.centralwidget)
#         self.ToolsBTN.move(50, 350)
#         MainWindow.setCentralWidget(self.centralwidget)
#
#
# class UIToolTab(object):
#     def setupUI(self, MainWindow):
#         MainWindow.setGeometry(50, 50, 400, 450)
#         MainWindow.setFixedSize(400, 450)
#         MainWindow.setWindowTitle("UIToolTab")
#         self.centralwidget = QWidget(MainWindow)
#         self.CPSBTN = QPushButton("text2", self.centralwidget)
#         self.CPSBTN.move(100, 350)
#         MainWindow.setCentralWidget(self.centralwidget)
#
#
# class MainWindow(QMainWindow):
#     def __init__(self, parent=None):
#         super(MainWindow, self).__init__(parent)
#         self.uiWindow = UIWindow()
#         self.uiToolTab = UIToolTab()
#         self.startUIWindow()
#
#     def startUIToolTab(self):
#         self.uiToolTab.setupUI(self)
#         self.uiToolTab.CPSBTN.clicked.connect(self.startUIWindow)
#         self.show()
#
#     def startUIWindow(self):
#         self.uiWindow.setupUI(self)
#         self.uiWindow.ToolsBTN.clicked.connect(self.startUIToolTab)
#         self.show()
#
#
# if __name__ == '__main__':
#     app = QApplication(sys.argv)
#     w = MainWindow()
#     sys.exit(app.exec_())